import '@fortawesome/fontawesome-pro/js/all'
// import '@fortawesome/fontawesome-pro/js/brands'
// import '@fortawesome/fontawesome-pro/js/duotone'
// import '@fortawesome/fontawesome-pro/js/light'
// import '@fortawesome/fontawesome-pro/js/regular'
// import '@fortawesome/fontawesome-pro/js/solid'
// import '@fortawesome/fontawesome-pro/js/thin'